project_name: base16-builder-go
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
dockers:
-
  goos: linux
  goarch: amd64
  use: buildx
  image_templates:
  - "ghcr.io/tinted-theming/base16-builder-go:{{ .Tag }}-amd64"
  extra_files:
  - entrypoint.sh
  build_flag_templates:
  - "--platform=linux/amd64"
docker_manifests:
- name_template: "ghcr.io/tinted-theming/base16-builder-go:{{ .Tag }}"
  image_templates:
  - "ghcr.io/tinted-theming/base16-builder-go:{{ .Tag }}-amd64"
- name_template: "ghcr.io/tinted-theming/base16-builder-go:v{{ .Major }}.{{ .Minor }}"
  image_templates:
  - "ghcr.io/tinted-theming/base16-builder-go:{{ .Tag }}-amd64"
- name_template: "ghcr.io/tinted-theming/base16-builder-go:latest"
  image_templates:
  - "ghcr.io/tinted-theming/base16-builder-go:{{ .Tag }}-amd64"
archives:
- format: binary
  replacements:
    amd64: x86_64
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
